spring:
  cloud:
    function:
      definition: memberConsumer;logConsumer
    stream:
      bindings:
        memberConsumer-in-0:
          destination: member-topic
          group: member-sub
        logConsumer-in-0:
          destination: log-topic
          group: log-sub

  pulsar:
    client:
      service-url: pulsar://localhost:6650
